/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedFamiliesRouteImport } from './routes/_authenticated/families'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedVaultFamilyIdRouteImport } from './routes/_authenticated/vault.$familyId'
import { Route as AuthenticatedUpcomingFamilyIdRouteImport } from './routes/_authenticated/upcoming.$familyId'
import { Route as AuthenticatedTransfersFamilyIdRouteImport } from './routes/_authenticated/transfers.$familyId'
import { Route as AuthenticatedSettingsFamilyIdRouteImport } from './routes/_authenticated/settings.$familyId'
import { Route as AuthenticatedSavingsFamilyIdRouteImport } from './routes/_authenticated/savings.$familyId'
import { Route as AuthenticatedPersonalVaultRouteImport } from './routes/_authenticated/personal/vault'
import { Route as AuthenticatedPersonalUpcomingRouteImport } from './routes/_authenticated/personal/upcoming'
import { Route as AuthenticatedPersonalTransfersRouteImport } from './routes/_authenticated/personal/transfers'
import { Route as AuthenticatedPersonalSavingsRouteImport } from './routes/_authenticated/personal/savings'
import { Route as AuthenticatedPersonalInsuranceRouteImport } from './routes/_authenticated/personal/insurance'
import { Route as AuthenticatedPersonalIncomeRouteImport } from './routes/_authenticated/personal/income'
import { Route as AuthenticatedPersonalFriendsRouteImport } from './routes/_authenticated/personal/friends'
import { Route as AuthenticatedPersonalExpensesRouteImport } from './routes/_authenticated/personal/expenses'
import { Route as AuthenticatedPersonalDebtsRouteImport } from './routes/_authenticated/personal/debts'
import { Route as AuthenticatedPersonalDashboardRouteImport } from './routes/_authenticated/personal/dashboard'
import { Route as AuthenticatedPersonalAssetsRouteImport } from './routes/_authenticated/personal/assets'
import { Route as AuthenticatedInsuranceFamilyIdRouteImport } from './routes/_authenticated/insurance.$familyId'
import { Route as AuthenticatedIncomeFamilyIdRouteImport } from './routes/_authenticated/income.$familyId'
import { Route as AuthenticatedExpensesFamilyIdRouteImport } from './routes/_authenticated/expenses.$familyId'
import { Route as AuthenticatedDebtsFamilyIdRouteImport } from './routes/_authenticated/debts.$familyId'
import { Route as AuthenticatedDashboardFamilyIdRouteImport } from './routes/_authenticated/dashboard.$familyId'
import { Route as AuthenticatedAssetsFamilyIdRouteImport } from './routes/_authenticated/assets.$familyId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminFamiliesRouteImport } from './routes/_authenticated/admin.families'
import { Route as AuthenticatedAdminCurrenciesRouteImport } from './routes/_authenticated/admin.currencies'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFamiliesRoute = AuthenticatedFamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedVaultFamilyIdRoute =
  AuthenticatedVaultFamilyIdRouteImport.update({
    id: '/vault/$familyId',
    path: '/vault/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUpcomingFamilyIdRoute =
  AuthenticatedUpcomingFamilyIdRouteImport.update({
    id: '/upcoming/$familyId',
    path: '/upcoming/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransfersFamilyIdRoute =
  AuthenticatedTransfersFamilyIdRouteImport.update({
    id: '/transfers/$familyId',
    path: '/transfers/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsFamilyIdRoute =
  AuthenticatedSettingsFamilyIdRouteImport.update({
    id: '/settings/$familyId',
    path: '/settings/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSavingsFamilyIdRoute =
  AuthenticatedSavingsFamilyIdRouteImport.update({
    id: '/savings/$familyId',
    path: '/savings/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalVaultRoute =
  AuthenticatedPersonalVaultRouteImport.update({
    id: '/personal/vault',
    path: '/personal/vault',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalUpcomingRoute =
  AuthenticatedPersonalUpcomingRouteImport.update({
    id: '/personal/upcoming',
    path: '/personal/upcoming',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalTransfersRoute =
  AuthenticatedPersonalTransfersRouteImport.update({
    id: '/personal/transfers',
    path: '/personal/transfers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalSavingsRoute =
  AuthenticatedPersonalSavingsRouteImport.update({
    id: '/personal/savings',
    path: '/personal/savings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalInsuranceRoute =
  AuthenticatedPersonalInsuranceRouteImport.update({
    id: '/personal/insurance',
    path: '/personal/insurance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalIncomeRoute =
  AuthenticatedPersonalIncomeRouteImport.update({
    id: '/personal/income',
    path: '/personal/income',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalFriendsRoute =
  AuthenticatedPersonalFriendsRouteImport.update({
    id: '/personal/friends',
    path: '/personal/friends',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalExpensesRoute =
  AuthenticatedPersonalExpensesRouteImport.update({
    id: '/personal/expenses',
    path: '/personal/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalDebtsRoute =
  AuthenticatedPersonalDebtsRouteImport.update({
    id: '/personal/debts',
    path: '/personal/debts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalDashboardRoute =
  AuthenticatedPersonalDashboardRouteImport.update({
    id: '/personal/dashboard',
    path: '/personal/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonalAssetsRoute =
  AuthenticatedPersonalAssetsRouteImport.update({
    id: '/personal/assets',
    path: '/personal/assets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsuranceFamilyIdRoute =
  AuthenticatedInsuranceFamilyIdRouteImport.update({
    id: '/insurance/$familyId',
    path: '/insurance/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomeFamilyIdRoute =
  AuthenticatedIncomeFamilyIdRouteImport.update({
    id: '/income/$familyId',
    path: '/income/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesFamilyIdRoute =
  AuthenticatedExpensesFamilyIdRouteImport.update({
    id: '/expenses/$familyId',
    path: '/expenses/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDebtsFamilyIdRoute =
  AuthenticatedDebtsFamilyIdRouteImport.update({
    id: '/debts/$familyId',
    path: '/debts/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardFamilyIdRoute =
  AuthenticatedDashboardFamilyIdRouteImport.update({
    id: '/dashboard/$familyId',
    path: '/dashboard/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsFamilyIdRoute =
  AuthenticatedAssetsFamilyIdRouteImport.update({
    id: '/assets/$familyId',
    path: '/assets/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFamiliesRoute =
  AuthenticatedAdminFamiliesRouteImport.update({
    id: '/families',
    path: '/families',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCurrenciesRoute =
  AuthenticatedAdminCurrenciesRouteImport.update({
    id: '/currencies',
    path: '/currencies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/families': typeof AuthenticatedFamiliesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/currencies': typeof AuthenticatedAdminCurrenciesRoute
  '/admin/families': typeof AuthenticatedAdminFamiliesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/assets/$familyId': typeof AuthenticatedAssetsFamilyIdRoute
  '/dashboard/$familyId': typeof AuthenticatedDashboardFamilyIdRoute
  '/debts/$familyId': typeof AuthenticatedDebtsFamilyIdRoute
  '/expenses/$familyId': typeof AuthenticatedExpensesFamilyIdRoute
  '/income/$familyId': typeof AuthenticatedIncomeFamilyIdRoute
  '/insurance/$familyId': typeof AuthenticatedInsuranceFamilyIdRoute
  '/personal/assets': typeof AuthenticatedPersonalAssetsRoute
  '/personal/dashboard': typeof AuthenticatedPersonalDashboardRoute
  '/personal/debts': typeof AuthenticatedPersonalDebtsRoute
  '/personal/expenses': typeof AuthenticatedPersonalExpensesRoute
  '/personal/friends': typeof AuthenticatedPersonalFriendsRoute
  '/personal/income': typeof AuthenticatedPersonalIncomeRoute
  '/personal/insurance': typeof AuthenticatedPersonalInsuranceRoute
  '/personal/savings': typeof AuthenticatedPersonalSavingsRoute
  '/personal/transfers': typeof AuthenticatedPersonalTransfersRoute
  '/personal/upcoming': typeof AuthenticatedPersonalUpcomingRoute
  '/personal/vault': typeof AuthenticatedPersonalVaultRoute
  '/savings/$familyId': typeof AuthenticatedSavingsFamilyIdRoute
  '/settings/$familyId': typeof AuthenticatedSettingsFamilyIdRoute
  '/transfers/$familyId': typeof AuthenticatedTransfersFamilyIdRoute
  '/upcoming/$familyId': typeof AuthenticatedUpcomingFamilyIdRoute
  '/vault/$familyId': typeof AuthenticatedVaultFamilyIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/families': typeof AuthenticatedFamiliesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/currencies': typeof AuthenticatedAdminCurrenciesRoute
  '/admin/families': typeof AuthenticatedAdminFamiliesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/assets/$familyId': typeof AuthenticatedAssetsFamilyIdRoute
  '/dashboard/$familyId': typeof AuthenticatedDashboardFamilyIdRoute
  '/debts/$familyId': typeof AuthenticatedDebtsFamilyIdRoute
  '/expenses/$familyId': typeof AuthenticatedExpensesFamilyIdRoute
  '/income/$familyId': typeof AuthenticatedIncomeFamilyIdRoute
  '/insurance/$familyId': typeof AuthenticatedInsuranceFamilyIdRoute
  '/personal/assets': typeof AuthenticatedPersonalAssetsRoute
  '/personal/dashboard': typeof AuthenticatedPersonalDashboardRoute
  '/personal/debts': typeof AuthenticatedPersonalDebtsRoute
  '/personal/expenses': typeof AuthenticatedPersonalExpensesRoute
  '/personal/friends': typeof AuthenticatedPersonalFriendsRoute
  '/personal/income': typeof AuthenticatedPersonalIncomeRoute
  '/personal/insurance': typeof AuthenticatedPersonalInsuranceRoute
  '/personal/savings': typeof AuthenticatedPersonalSavingsRoute
  '/personal/transfers': typeof AuthenticatedPersonalTransfersRoute
  '/personal/upcoming': typeof AuthenticatedPersonalUpcomingRoute
  '/personal/vault': typeof AuthenticatedPersonalVaultRoute
  '/savings/$familyId': typeof AuthenticatedSavingsFamilyIdRoute
  '/settings/$familyId': typeof AuthenticatedSettingsFamilyIdRoute
  '/transfers/$familyId': typeof AuthenticatedTransfersFamilyIdRoute
  '/upcoming/$familyId': typeof AuthenticatedUpcomingFamilyIdRoute
  '/vault/$familyId': typeof AuthenticatedVaultFamilyIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/families': typeof AuthenticatedFamiliesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/currencies': typeof AuthenticatedAdminCurrenciesRoute
  '/_authenticated/admin/families': typeof AuthenticatedAdminFamiliesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/assets/$familyId': typeof AuthenticatedAssetsFamilyIdRoute
  '/_authenticated/dashboard/$familyId': typeof AuthenticatedDashboardFamilyIdRoute
  '/_authenticated/debts/$familyId': typeof AuthenticatedDebtsFamilyIdRoute
  '/_authenticated/expenses/$familyId': typeof AuthenticatedExpensesFamilyIdRoute
  '/_authenticated/income/$familyId': typeof AuthenticatedIncomeFamilyIdRoute
  '/_authenticated/insurance/$familyId': typeof AuthenticatedInsuranceFamilyIdRoute
  '/_authenticated/personal/assets': typeof AuthenticatedPersonalAssetsRoute
  '/_authenticated/personal/dashboard': typeof AuthenticatedPersonalDashboardRoute
  '/_authenticated/personal/debts': typeof AuthenticatedPersonalDebtsRoute
  '/_authenticated/personal/expenses': typeof AuthenticatedPersonalExpensesRoute
  '/_authenticated/personal/friends': typeof AuthenticatedPersonalFriendsRoute
  '/_authenticated/personal/income': typeof AuthenticatedPersonalIncomeRoute
  '/_authenticated/personal/insurance': typeof AuthenticatedPersonalInsuranceRoute
  '/_authenticated/personal/savings': typeof AuthenticatedPersonalSavingsRoute
  '/_authenticated/personal/transfers': typeof AuthenticatedPersonalTransfersRoute
  '/_authenticated/personal/upcoming': typeof AuthenticatedPersonalUpcomingRoute
  '/_authenticated/personal/vault': typeof AuthenticatedPersonalVaultRoute
  '/_authenticated/savings/$familyId': typeof AuthenticatedSavingsFamilyIdRoute
  '/_authenticated/settings/$familyId': typeof AuthenticatedSettingsFamilyIdRoute
  '/_authenticated/transfers/$familyId': typeof AuthenticatedTransfersFamilyIdRoute
  '/_authenticated/upcoming/$familyId': typeof AuthenticatedUpcomingFamilyIdRoute
  '/_authenticated/vault/$familyId': typeof AuthenticatedVaultFamilyIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/admin'
    | '/families'
    | '/notifications'
    | '/profile'
    | '/admin/currencies'
    | '/admin/families'
    | '/admin/users'
    | '/assets/$familyId'
    | '/dashboard/$familyId'
    | '/debts/$familyId'
    | '/expenses/$familyId'
    | '/income/$familyId'
    | '/insurance/$familyId'
    | '/personal/assets'
    | '/personal/dashboard'
    | '/personal/debts'
    | '/personal/expenses'
    | '/personal/friends'
    | '/personal/income'
    | '/personal/insurance'
    | '/personal/savings'
    | '/personal/transfers'
    | '/personal/upcoming'
    | '/personal/vault'
    | '/savings/$familyId'
    | '/settings/$familyId'
    | '/transfers/$familyId'
    | '/upcoming/$familyId'
    | '/vault/$familyId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/families'
    | '/notifications'
    | '/profile'
    | '/admin/currencies'
    | '/admin/families'
    | '/admin/users'
    | '/assets/$familyId'
    | '/dashboard/$familyId'
    | '/debts/$familyId'
    | '/expenses/$familyId'
    | '/income/$familyId'
    | '/insurance/$familyId'
    | '/personal/assets'
    | '/personal/dashboard'
    | '/personal/debts'
    | '/personal/expenses'
    | '/personal/friends'
    | '/personal/income'
    | '/personal/insurance'
    | '/personal/savings'
    | '/personal/transfers'
    | '/personal/upcoming'
    | '/personal/vault'
    | '/savings/$familyId'
    | '/settings/$familyId'
    | '/transfers/$familyId'
    | '/upcoming/$familyId'
    | '/vault/$familyId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/families'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/admin/currencies'
    | '/_authenticated/admin/families'
    | '/_authenticated/admin/users'
    | '/_authenticated/assets/$familyId'
    | '/_authenticated/dashboard/$familyId'
    | '/_authenticated/debts/$familyId'
    | '/_authenticated/expenses/$familyId'
    | '/_authenticated/income/$familyId'
    | '/_authenticated/insurance/$familyId'
    | '/_authenticated/personal/assets'
    | '/_authenticated/personal/dashboard'
    | '/_authenticated/personal/debts'
    | '/_authenticated/personal/expenses'
    | '/_authenticated/personal/friends'
    | '/_authenticated/personal/income'
    | '/_authenticated/personal/insurance'
    | '/_authenticated/personal/savings'
    | '/_authenticated/personal/transfers'
    | '/_authenticated/personal/upcoming'
    | '/_authenticated/personal/vault'
    | '/_authenticated/savings/$familyId'
    | '/_authenticated/settings/$familyId'
    | '/_authenticated/transfers/$familyId'
    | '/_authenticated/upcoming/$familyId'
    | '/_authenticated/vault/$familyId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/families': {
      id: '/_authenticated/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof AuthenticatedFamiliesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/vault/$familyId': {
      id: '/_authenticated/vault/$familyId'
      path: '/vault/$familyId'
      fullPath: '/vault/$familyId'
      preLoaderRoute: typeof AuthenticatedVaultFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upcoming/$familyId': {
      id: '/_authenticated/upcoming/$familyId'
      path: '/upcoming/$familyId'
      fullPath: '/upcoming/$familyId'
      preLoaderRoute: typeof AuthenticatedUpcomingFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfers/$familyId': {
      id: '/_authenticated/transfers/$familyId'
      path: '/transfers/$familyId'
      fullPath: '/transfers/$familyId'
      preLoaderRoute: typeof AuthenticatedTransfersFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/$familyId': {
      id: '/_authenticated/settings/$familyId'
      path: '/settings/$familyId'
      fullPath: '/settings/$familyId'
      preLoaderRoute: typeof AuthenticatedSettingsFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/savings/$familyId': {
      id: '/_authenticated/savings/$familyId'
      path: '/savings/$familyId'
      fullPath: '/savings/$familyId'
      preLoaderRoute: typeof AuthenticatedSavingsFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/vault': {
      id: '/_authenticated/personal/vault'
      path: '/personal/vault'
      fullPath: '/personal/vault'
      preLoaderRoute: typeof AuthenticatedPersonalVaultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/upcoming': {
      id: '/_authenticated/personal/upcoming'
      path: '/personal/upcoming'
      fullPath: '/personal/upcoming'
      preLoaderRoute: typeof AuthenticatedPersonalUpcomingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/transfers': {
      id: '/_authenticated/personal/transfers'
      path: '/personal/transfers'
      fullPath: '/personal/transfers'
      preLoaderRoute: typeof AuthenticatedPersonalTransfersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/savings': {
      id: '/_authenticated/personal/savings'
      path: '/personal/savings'
      fullPath: '/personal/savings'
      preLoaderRoute: typeof AuthenticatedPersonalSavingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/insurance': {
      id: '/_authenticated/personal/insurance'
      path: '/personal/insurance'
      fullPath: '/personal/insurance'
      preLoaderRoute: typeof AuthenticatedPersonalInsuranceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/income': {
      id: '/_authenticated/personal/income'
      path: '/personal/income'
      fullPath: '/personal/income'
      preLoaderRoute: typeof AuthenticatedPersonalIncomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/friends': {
      id: '/_authenticated/personal/friends'
      path: '/personal/friends'
      fullPath: '/personal/friends'
      preLoaderRoute: typeof AuthenticatedPersonalFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/expenses': {
      id: '/_authenticated/personal/expenses'
      path: '/personal/expenses'
      fullPath: '/personal/expenses'
      preLoaderRoute: typeof AuthenticatedPersonalExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/debts': {
      id: '/_authenticated/personal/debts'
      path: '/personal/debts'
      fullPath: '/personal/debts'
      preLoaderRoute: typeof AuthenticatedPersonalDebtsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/dashboard': {
      id: '/_authenticated/personal/dashboard'
      path: '/personal/dashboard'
      fullPath: '/personal/dashboard'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal/assets': {
      id: '/_authenticated/personal/assets'
      path: '/personal/assets'
      fullPath: '/personal/assets'
      preLoaderRoute: typeof AuthenticatedPersonalAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insurance/$familyId': {
      id: '/_authenticated/insurance/$familyId'
      path: '/insurance/$familyId'
      fullPath: '/insurance/$familyId'
      preLoaderRoute: typeof AuthenticatedInsuranceFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income/$familyId': {
      id: '/_authenticated/income/$familyId'
      path: '/income/$familyId'
      fullPath: '/income/$familyId'
      preLoaderRoute: typeof AuthenticatedIncomeFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/$familyId': {
      id: '/_authenticated/expenses/$familyId'
      path: '/expenses/$familyId'
      fullPath: '/expenses/$familyId'
      preLoaderRoute: typeof AuthenticatedExpensesFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/debts/$familyId': {
      id: '/_authenticated/debts/$familyId'
      path: '/debts/$familyId'
      fullPath: '/debts/$familyId'
      preLoaderRoute: typeof AuthenticatedDebtsFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/$familyId': {
      id: '/_authenticated/dashboard/$familyId'
      path: '/dashboard/$familyId'
      fullPath: '/dashboard/$familyId'
      preLoaderRoute: typeof AuthenticatedDashboardFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/$familyId': {
      id: '/_authenticated/assets/$familyId'
      path: '/assets/$familyId'
      fullPath: '/assets/$familyId'
      preLoaderRoute: typeof AuthenticatedAssetsFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/families': {
      id: '/_authenticated/admin/families'
      path: '/families'
      fullPath: '/admin/families'
      preLoaderRoute: typeof AuthenticatedAdminFamiliesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/currencies': {
      id: '/_authenticated/admin/currencies'
      path: '/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AuthenticatedAdminCurrenciesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCurrenciesRoute: typeof AuthenticatedAdminCurrenciesRoute
  AuthenticatedAdminFamiliesRoute: typeof AuthenticatedAdminFamiliesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCurrenciesRoute: AuthenticatedAdminCurrenciesRoute,
  AuthenticatedAdminFamiliesRoute: AuthenticatedAdminFamiliesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedFamiliesRoute: typeof AuthenticatedFamiliesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAssetsFamilyIdRoute: typeof AuthenticatedAssetsFamilyIdRoute
  AuthenticatedDashboardFamilyIdRoute: typeof AuthenticatedDashboardFamilyIdRoute
  AuthenticatedDebtsFamilyIdRoute: typeof AuthenticatedDebtsFamilyIdRoute
  AuthenticatedExpensesFamilyIdRoute: typeof AuthenticatedExpensesFamilyIdRoute
  AuthenticatedIncomeFamilyIdRoute: typeof AuthenticatedIncomeFamilyIdRoute
  AuthenticatedInsuranceFamilyIdRoute: typeof AuthenticatedInsuranceFamilyIdRoute
  AuthenticatedPersonalAssetsRoute: typeof AuthenticatedPersonalAssetsRoute
  AuthenticatedPersonalDashboardRoute: typeof AuthenticatedPersonalDashboardRoute
  AuthenticatedPersonalDebtsRoute: typeof AuthenticatedPersonalDebtsRoute
  AuthenticatedPersonalExpensesRoute: typeof AuthenticatedPersonalExpensesRoute
  AuthenticatedPersonalFriendsRoute: typeof AuthenticatedPersonalFriendsRoute
  AuthenticatedPersonalIncomeRoute: typeof AuthenticatedPersonalIncomeRoute
  AuthenticatedPersonalInsuranceRoute: typeof AuthenticatedPersonalInsuranceRoute
  AuthenticatedPersonalSavingsRoute: typeof AuthenticatedPersonalSavingsRoute
  AuthenticatedPersonalTransfersRoute: typeof AuthenticatedPersonalTransfersRoute
  AuthenticatedPersonalUpcomingRoute: typeof AuthenticatedPersonalUpcomingRoute
  AuthenticatedPersonalVaultRoute: typeof AuthenticatedPersonalVaultRoute
  AuthenticatedSavingsFamilyIdRoute: typeof AuthenticatedSavingsFamilyIdRoute
  AuthenticatedSettingsFamilyIdRoute: typeof AuthenticatedSettingsFamilyIdRoute
  AuthenticatedTransfersFamilyIdRoute: typeof AuthenticatedTransfersFamilyIdRoute
  AuthenticatedUpcomingFamilyIdRoute: typeof AuthenticatedUpcomingFamilyIdRoute
  AuthenticatedVaultFamilyIdRoute: typeof AuthenticatedVaultFamilyIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedFamiliesRoute: AuthenticatedFamiliesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAssetsFamilyIdRoute: AuthenticatedAssetsFamilyIdRoute,
  AuthenticatedDashboardFamilyIdRoute: AuthenticatedDashboardFamilyIdRoute,
  AuthenticatedDebtsFamilyIdRoute: AuthenticatedDebtsFamilyIdRoute,
  AuthenticatedExpensesFamilyIdRoute: AuthenticatedExpensesFamilyIdRoute,
  AuthenticatedIncomeFamilyIdRoute: AuthenticatedIncomeFamilyIdRoute,
  AuthenticatedInsuranceFamilyIdRoute: AuthenticatedInsuranceFamilyIdRoute,
  AuthenticatedPersonalAssetsRoute: AuthenticatedPersonalAssetsRoute,
  AuthenticatedPersonalDashboardRoute: AuthenticatedPersonalDashboardRoute,
  AuthenticatedPersonalDebtsRoute: AuthenticatedPersonalDebtsRoute,
  AuthenticatedPersonalExpensesRoute: AuthenticatedPersonalExpensesRoute,
  AuthenticatedPersonalFriendsRoute: AuthenticatedPersonalFriendsRoute,
  AuthenticatedPersonalIncomeRoute: AuthenticatedPersonalIncomeRoute,
  AuthenticatedPersonalInsuranceRoute: AuthenticatedPersonalInsuranceRoute,
  AuthenticatedPersonalSavingsRoute: AuthenticatedPersonalSavingsRoute,
  AuthenticatedPersonalTransfersRoute: AuthenticatedPersonalTransfersRoute,
  AuthenticatedPersonalUpcomingRoute: AuthenticatedPersonalUpcomingRoute,
  AuthenticatedPersonalVaultRoute: AuthenticatedPersonalVaultRoute,
  AuthenticatedSavingsFamilyIdRoute: AuthenticatedSavingsFamilyIdRoute,
  AuthenticatedSettingsFamilyIdRoute: AuthenticatedSettingsFamilyIdRoute,
  AuthenticatedTransfersFamilyIdRoute: AuthenticatedTransfersFamilyIdRoute,
  AuthenticatedUpcomingFamilyIdRoute: AuthenticatedUpcomingFamilyIdRoute,
  AuthenticatedVaultFamilyIdRoute: AuthenticatedVaultFamilyIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
